"use server";

/**
 * Prototype Studio — Server Actions (Phase A)
 * ==========================================
 * كل تعديل محمي بـ RBAC (owner + admin + supervisor). لا AI. لا API خارجي.
 */
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/auth/rbac";
import { saveConfig, type SaveConfigPatch } from "@/lib/prototype-studio/config-service";
import {
  createArtifact, listArtifacts,
} from "@/lib/prototype-studio/artifact-service";
import { buildContextPackMarkdown } from "@/lib/prototype-studio/context-pack-builder";
import type {
  ArtifactType, PrototypeStudioArtifactRow,
} from "@/lib/prototype-studio/types";

type ActionResult<T = void> = { ok: true; data?: T } | { ok: false; message: string };
const WRITE_ROLES = ["owner", "admin", "supervisor"] as const;

async function guard() {
  const gate = await requireRole([...WRITE_ROLES]);
  if (!gate.ok) return { ok: false as const, message: gate.message ?? "غير مصرَّح" };
  return { ok: true as const, userId: gate.userId ?? null };
}

export async function saveStudioConfigAction(
  projectId: string,
  patch: SaveConfigPatch,
): Promise<ActionResult> {
  const g = await guard();
  if (!g.ok) return g;
  try {
    await saveConfig(projectId, patch, g.userId);
    revalidatePath(`/dashboard/projects/${projectId}`);
    return { ok: true };
  } catch (e) {
    return { ok: false, message: e instanceof Error ? e.message : "فشل الحفظ." };
  }
}

export interface GenerateContextPackResult {
  artifactId: string;
  version: number;
  missing: string[];
}

export async function generateContextPackAction(
  projectId: string,
): Promise<ActionResult<GenerateContextPackResult>> {
  const g = await guard();
  if (!g.ok) return g;
  try {
    const built = await buildContextPackMarkdown(projectId);
    const row = await createArtifact(
      projectId,
      "context_pack",
      built.md,
      {
        pinned_prd_version: built.pinnedPrdVersion,
        pinned_brain_version: built.pinnedBrainVersion,
        pinned_config_updated_at: built.pinnedConfigUpdatedAt,
        chatgpt_session_ref: null,
        source_details: `generated by system; missing=${built.missing.length}`,
      },
      "system",
      g.userId,
      "",
      "active",
    );
    revalidatePath(`/dashboard/projects/${projectId}`);
    return { ok: true, data: { artifactId: row.id, version: row.version, missing: built.missing } };
  } catch (e) {
    return { ok: false, message: e instanceof Error ? e.message : "فشل توليد Context Pack." };
  }
}

export async function listStudioArtifactsAction(
  projectId: string,
  type?: ArtifactType,
): Promise<ActionResult<PrototypeStudioArtifactRow[]>> {
  try {
    const rows = await listArtifacts(projectId, type);
    return { ok: true, data: rows };
  } catch (e) {
    return { ok: false, message: e instanceof Error ? e.message : "فشل القراءة." };
  }
}
