import type { StageDefinition, WorkflowAction, WorkflowRole } from "./types";

/** اختصار لتعريف صلاحيات مرحلة من غير تكرار الشكل الكامل كل مرة. */
function perms(
  overrides: Partial<Record<WorkflowAction, WorkflowRole[]>> = {}
): Record<WorkflowAction, WorkflowRole[]> {
  return {
    view: ["admin", "pm", "reviewer", "developer", "qa", "support"],
    edit: ["admin", "pm"],
    approve: ["admin", "pm", "reviewer"],
    regenerate: ["admin", "pm"],
    archive: ["admin"],
    ...overrides,
  };
}

/**
 * الترتيب/الاعتماديات/الصلاحيات مصدرها الوحيد الملف ده — بديل project-
 * tabs.tsx اللي كان بيحدد الترتيب جوّه Array حرفي في مكوّن React. كل
 * محرك حالي (PRD/Prototype Prompt/Engineering QA/...) فاضل شغّال زي ما
 * هو تمامًا؛ الملف ده بس واصف ميتاداتا للتنقّل والتبعية والصلاحيات.
 *
 * ملحوظتين مهمّتين اتفق عليهم صاحب المنتج صراحة قبل التنفيذ:
 * - "Client Presentation" اتّرقّت لمرحلة مستقلّة "clientDelivery" بعد
 *   Developer Handoff (عرض تنفيذي جاهز للعميل يُجمَّع من كل المراحل)،
 *   بقرار صريح من صاحب المنتج بنقلها من كونها تبويب فرعي جوّه
 *   "prototypeReview". و"AI Code Execution" (بمحتواه الكامل: خطة
 *   التنفيذ + المهام + QA Fix Loop) هو المحتوى الفعلي لمرحلة
 *   "promptReview".
 * - "Fix Prompt" و"Engineering QA Review" و"Production Monitoring
 *   Prompt" و"Production Monitoring Review" مراحل جديدة بتُبنى على
 *   بيانات موجودة فعليًا (مفيش جداول جديدة لمحتواها) — مفصّل في
 *   lib/workflow/adapters/.
 */
export const STAGE_REGISTRY: StageDefinition[] = [
  {
    id: "discovery",
    slug: "discovery",
    displayName: "Discovery",
    description: "فورم الاكتشاف الأولي وربطه بالعميل.",
    icon: "ClipboardList",
    order: 1,
    dependencies: [],
    entryConditions: "المشروع اتنشأ.",
    exitConditions: "فورم الاكتشاف اتملى (من العميل أو من الفريق).",
    permissions: perms(),
  },
  {
    id: "overview",
    slug: "overview",
    displayName: "نظرة عامة",
    description: "(دُمج داخل التبويبات: ManualNoteComposer + AnalysisPanel → analysis، ProjectBrainEntries → projectBrain) ملاحظات المشروع العامة وتحليل الذكاء الاصطناعي الأولي.",
    icon: "LayoutDashboard",
    order: 2,
    dependencies: [],
    entryConditions: "المشروع اتنشأ.",
    exitConditions: "لا يوجد شرط خروج إلزامي — مرحلة مرجعية دايمة.",
    permissions: perms(),
  },
  {
    id: "analysis",
    slug: "analysis",
    displayName: "التحليل",
    description: "تحليل الذكاء الاصطناعي لإجابات الاكتشاف (Business Analyst persona).",
    icon: "SearchCheck",
    order: 3,
    dependencies: ["discovery"],
    entryConditions: "فورم الاكتشاف مكتمل.",
    exitConditions: "التحليل اكتمل (status = completed).",
    permissions: perms({ edit: ["admin", "pm"], approve: ["admin", "pm", "reviewer"] }),
  },
  {
    id: "meetingPreparation",
    slug: "meeting-preparation",
    displayName: "تجهيز الاجتماع",
    description: "(دُمج داخل تبويب «الاجتماعات» كقسم فرعي «تجهيز الاجتماع») 13 مولّد مستقل يجهّزوا أجندة/أسئلة/سيناريوهات الاجتماع الأول.",
    icon: "CalendarClock",
    order: 4,
    dependencies: ["analysis"],
    entryConditions: "التحليل مكتمل.",
    exitConditions: "تجهيز الاجتماع اتولّد.",
    permissions: perms(),
  },
  {
    id: "meetingPresentation",
    slug: "meeting-presentation",
    displayName: "عرض الاجتماع",
    description: "(دُمج داخل تبويب «الاجتماعات» كقسم فرعي «عرض الاجتماع») الديك المرئي (15 شريحة) + وضع العرض المباشر أثناء الاجتماع.",
    icon: "Presentation",
    order: 5,
    dependencies: ["meetingPreparation"],
    entryConditions: "تجهيز الاجتماع مكتمل.",
    exitConditions: "الديك اتولّد وجاهز للعرض.",
    permissions: perms(),
  },
  {
    id: "meetings",
    slug: "meetings",
    displayName: "الاجتماعات",
    description: "سجل الاجتماعات الفعلية (تسجيل عبر تليجرام → تفريغ → تحليل → مراجعة).",
    icon: "Users",
    order: 6,
    dependencies: ["meetingPresentation"],
    entryConditions: "فيه اجتماع اتسجّل أو تم جدولته.",
    exitConditions: "الاجتماع انتهى وتحليله اكتمل.",
    permissions: perms(),
  },
  {
    id: "deliveryMilestones",
    slug: "delivery-milestones",
    displayName: "مراحل التسليم",
    description: "خطة التسليمات (نماذج/وحدات/Beta/RC/نهائي) ومهامها ونسبة إنجازها واعتماد العميل.",
    icon: "Flag",
    order: 6.5,
    dependencies: ["meetings"],
    entryConditions: "المشروع في مرحلة تنفيذ (بعد الاجتماعات الأولى).",
    exitConditions: "كل مراحل التسليم معتمدة (approved).",
    permissions: perms({ approve: ["admin", "pm"] }),
  },
  {
    id: "knowledgeHub",
    slug: "knowledge-hub",
    displayName: "مركز المعرفة",
    description:
      "المستندات اللي المعرفة الحقيقية جوّاها: سياسات، إجراءات تشغيل، أدلة، دراسات، مخططات، عقود، أبحاث الفريق. كل ملف بيتحلّل ويتحوّل لعناصر معرفة مصنّفة، كل عنصر بيحمل اقتباسه الحرفي من مصدره.",
    icon: "Library",
    order: 6.7,
    // مالهاش اعتماديات عن قصد: المستندات بتوصل قبل الاكتشاف أحيانًا،
    // وإجبار ترتيب هنا كان هيمنع الفريق من بناء قاعدة المعرفة بدري.
    dependencies: [],
    entryConditions: "المشروع قائم — ارفع أي مستند متعلّق به.",
    exitConditions: "كل المصادر المرفوعة اتحلّلت، والفجوات المعرفية اتاخد فيها قرار.",
    permissions: perms(),
  },
  {
    id: "smartRecommendations",
    slug: "smart-recommendations",
    displayName: "توصيات ذكية",
    description:
      "(دُمج داخل تبويب «Project Brain» كقسم فرعي «التوصيات») توصيات معمارية وفنية مبنية على تحليل الاكتشاف + مشاريع سابقة مشابهة + شبكة المعرفة — بتتولّد **قبل** بناء Project Brain، والتوصيات المقبولة بتتغذّى فيه تحت قسم «توصيات معمارية وفنية».",
    icon: "Sparkles",
    order: 7,
    dependencies: ["analysis"],
    entryConditions: "تحليل الاكتشاف مكتمل (أو فيه إجابات اكتشاف كافية).",
    exitConditions: "مفيش أي توصية لسه بحالة 'مقترحة' — كلها لازم تاخد قرار.",
    permissions: perms(),
  },
  {
    id: "projectBrain",
    slug: "brain",
    displayName: "Project Brain",
    description: "الوثيقة المركزية اللي بتلخّص فهم المشروع كله (19 قسم) — شاملة التوصيات المعمارية والفنية المقبولة من المرحلة السابقة.",
    icon: "BrainCircuit",
    order: 8,
    dependencies: ["analysis", "meetings", "smartRecommendations"],
    entryConditions: "التحليل مكتمل والتوصيات الذكية اتولّدت واتراجعت.",
    exitConditions: "Brain عنده نسخة معتمدة (approved).",
    permissions: perms({ approve: ["admin", "pm", "reviewer"] }),
  },
  {
    id: "brainReview",
    slug: "brain-review",
    displayName: "Brain Review",
    description: "(دُمج داخل تبويب «Project Brain» كقسم فرعي «مراجعة الاعتماد») لجنة مراجعة تنفيذية — يُراجع كل عنصر معرفة على حدة، ويشغّل تحقّق AI كامل (اكتمال/تعارضات/روابط اعتماد)، قبل اعتماد Project Brain كمصدر رسمي للـ PRD.",
    icon: "FileCheck2",
    order: 9,
    dependencies: ["projectBrain", "smartRecommendations"],
    entryConditions: "Project Brain عنده مسودة.",
    exitConditions: "كل الأقسام والعناصر الفردية اتراجعت واتعمل لها Approve، مفيش توصية ذكية معلّقة، مفيش مشكلة حرجة/عالية غير محلولة من تحقّق AI، ومفيش عنصر محتاج إعادة تحقّق.",
    permissions: perms({ approve: ["admin", "pm", "reviewer"] }),
  },
  {
    id: "prd",
    slug: "prd",
    displayName: "PRD",
    description: "وثيقة متطلبات المنتج، متولّدة من Project Brain المعتمد.",
    icon: "FileText",
    order: 10,
    dependencies: ["brainReview"],
    entryConditions: "فيه نسخة معتمدة من Project Brain.",
    exitConditions: "PRD اتولّد (version > 0).",
    permissions: perms(),
  },
  {
    id: "prototypeStudio",
    slug: "prototype-studio",
    displayName: "Prototype Studio",
    description: "استوديو النموذج الأولي — Context Pack + Design Direction + Build Brief + Codex Pack (manual-assisted، بدون AI مدفوع).",
    icon: "Palette",
    order: 10.5,
    dependencies: ["prd"],
    entryConditions: "PRD اتولّد.",
    exitConditions: "Build Brief معتمَد وCodex Build Pack جاهز.",
    permissions: perms(),
  },
  {
    id: "prototypePrompt",
    slug: "prototype-prompt",
    displayName: "Prototype Prompt (Legacy)",
    description: "البرومبت الكامل لبناء الـ Prototype، متولّد من PRD + Brain. Legacy — استخدم Prototype Studio بدلاً منه لما prototype_studio flag مفعّل.",
    icon: "Wand2",
    order: 11,
    dependencies: ["prd"],
    entryConditions: "PRD اتولّد.",
    exitConditions: "Prototype Prompt اتولّد (version > 0).",
    permissions: perms(),
  },
  {
    id: "prototypeReview",
    slug: "prototype-review",
    displayName: "Prototype Review",
    description: "مراجعة الـ Prototype الفعلي + عرض العميل (Client Presentation كتبويب فرعي هنا).",
    icon: "Eye",
    order: 12,
    dependencies: ["prototypePrompt"],
    entryConditions: "Prototype Prompt اتولّد.",
    exitConditions: "المراجعة اتولّدت (version > 0).",
    permissions: perms(),
  },
  {
    id: "promptReview",
    slug: "prompt-review",
    displayName: "Prompt Review",
    description: "مراجعة/اعتماد خطة تنفيذ Claude (Execution Plan) قبل بدء التنفيذ الفعلي على المستودع.",
    icon: "Terminal",
    order: 13,
    dependencies: ["prototypePrompt"],
    entryConditions: "Prototype Prompt معتمد ومتاح لتوليد خطة تنفيذ.",
    exitConditions: "خطة التنفيذ اتنفّذت بالكامل (كل الـ Tasks completed).",
    permissions: perms({ regenerate: ["admin"] }),
  },
  {
    id: "developerHandoff",
    slug: "developer-handoff",
    displayName: "Developer Handoff",
    description: "(دُمج داخل تبويب «حزمة التسليم» كقسم فرعي «الوثيقة التقنية») وثيقة التسليم الفنية للمطورين، متولّدة من PRD + Prototype Review + Brain.",
    icon: "PackageCheck",
    order: 14,
    dependencies: ["prd", "prototypeReview"],
    entryConditions: "فيه مراجعة Prototype معتمدة.",
    exitConditions: "Developer Handoff اتولّد (version > 0).",
    permissions: perms(),
  },
  {
    id: "clientDelivery",
    slug: "client-delivery",
    displayName: "Client Presentation & Executive Delivery",
    description: "عرض تنفيذي احترافي جاهز للعميل — يُجمَّع تلقائيًّا من كل المراحل (اكتشاف/اجتماعات/قرارات/Brain/PRD/توصيات) بلا أي تفاصيل تقنية. تصدير PDF/PPTX/HTML تفاعلي.",
    icon: "Presentation",
    order: 14.5,
    dependencies: ["developerHandoff"],
    entryConditions: "Brain معتمد + PRD متاح (أساس العرض التنفيذي).",
    exitConditions: "العرض التنفيذي اتولّد (version > 0) وجاهز للتقديم/المشاركة.",
    permissions: perms(),
  },
  {
    id: "engineeringQa",
    slug: "engineering-qa",
    displayName: "Engineering QA",
    description: "12 محور تدقيق هندسي مستقل (أمان/بنية/أداء/جودة كود/...) على المستودع الفعلي.",
    icon: "ShieldCheck",
    order: 15,
    dependencies: ["developerHandoff"],
    entryConditions: "Developer Handoff جاهز والمستودع موجود.",
    exitConditions: "كل المحاور اكتملت.",
    permissions: perms({ regenerate: ["admin"] }),
  },
  {
    id: "fixPrompt",
    slug: "fix-prompt",
    displayName: "Fix Prompt",
    description: "(دُمج داخل تبويب «Engineering QA» كقسم فرعي «حلقات الإصلاح» في v2) البرومبت المُولّد تلقائيًا لإصلاح مشاكل Engineering QA، وتنفيذه عبر Claude.",
    icon: "Wrench",
    order: 16,
    dependencies: ["engineeringQa"],
    entryConditions: "فيه Findings بخطورة تستوجب إصلاح (critical/high/medium).",
    exitConditions: "مهمة الإصلاح المولّدة اكتملت.",
    permissions: perms({ regenerate: ["admin"] }),
  },
  {
    id: "engineeringQaReview",
    slug: "engineering-qa-review",
    displayName: "Engineering QA Review",
    description: "(دُمج داخل تبويب «Engineering QA» كقسم فرعي «بوابة الاعتماد» في v2) بوابة اعتماد بشرية على نتيجة Engineering QA النهائية بعد أي إصلاحات.",
    icon: "BadgeCheck",
    order: 17,
    dependencies: ["fixPrompt", "engineeringQa"],
    entryConditions: "Engineering QA اكتملت (بعد آخر محاولة إصلاح لو وُجدت).",
    exitConditions: "تم اعتماد أو رفض النتيجة من مسؤول.",
    permissions: perms({ approve: ["admin", "pm", "qa"] }),
  },
  {
    id: "productionMonitoring",
    slug: "production-monitoring",
    displayName: "Production Monitoring",
    description: "مراقبة مستمرة بعد الإطلاق (فحوصات دورية + حوادث).",
    icon: "Activity",
    order: 18,
    dependencies: ["engineeringQaReview"],
    entryConditions: "المشروع في الإنتاج (production_url موجود).",
    exitConditions: "لا يوجد شرط إلزامي — مراقبة مستمرة.",
    permissions: perms(),
  },
  {
    id: "productionMonitoringPrompt",
    slug: "production-monitoring-prompt",
    displayName: "Production Monitoring Prompt",
    description: "(دُمج داخل تبويب «Production Monitoring» كقسم فرعي «برومبتات الإصلاح» في v2) تحليل الحوادث بالذكاء الاصطناعي وتوليد مجموعة Prompts إصلاح مقسّمة حسب المحور التقني (قاعدة بيانات/واجهة/API/Worker/اختبارات/نشر) جاهزة للمطوّر.",
    icon: "AlertTriangle",
    order: 19,
    dependencies: ["productionMonitoring"],
    entryConditions: "فيه حادثة (Incident) مفتوحة.",
    exitConditions: "الحادثة اتحلّلت واتولّدت مجموعة Prompts إصلاح لكل محور متأثر.",
    permissions: perms({ regenerate: ["admin"] }),
  },
  {
    id: "productionMonitoringReview",
    slug: "production-monitoring-review",
    displayName: "Production Monitoring Review",
    description: "(دُمج داخل تبويب «Production Monitoring» كقسم فرعي «بوابة الاعتماد» في v2) حكم AI لكل حادثة بعد الإصلاح (اتحلّت/جزئيًا/لسه موجودة/تراجع...) ودرجة Overall Fix Score محسوبة بالكود، ثم بوابة اعتماد بشرية على صحة الإنتاج الحالية.",
    icon: "BadgeCheck",
    order: 20,
    dependencies: ["productionMonitoringPrompt", "productionMonitoring"],
    entryConditions: "فيه فحص Production حديث.",
    exitConditions: "تم توليد تقرير حكم (Review Report) وتم اعتماد أو رفض حالة الإنتاج من مسؤول.",
    permissions: perms({ approve: ["admin", "pm", "qa"] }),
  },
  {
    id: "organizationalIntelligence",
    slug: "organizational-intelligence",
    displayName: "الذكاء التنظيمي",
    description: "استشارة AI Product Advisor + ذاكرة القرارات عبر المشاريع.",
    icon: "Network",
    order: 21,
    dependencies: ["productionMonitoringReview"],
    entryConditions: "لا يوجد شرط دخول إلزامي.",
    exitConditions: "لا يوجد شرط خروج إلزامي.",
    permissions: perms(),
  },
  {
    id: "support",
    slug: "support",
    displayName: "Support Requests",
    description: "طلبات الدعم الواردة من الـ Widget بعد الإطلاق.",
    icon: "LifeBuoy",
    order: 22,
    dependencies: ["productionMonitoringReview"],
    entryConditions: "المشروع عنده widget_key مفعّل.",
    exitConditions: "لا يوجد شرط إلزامي — دعم مستمر.",
    permissions: perms({ edit: ["admin", "pm", "support"] }),
  },
];

export function getStageDefinition(key: string): StageDefinition | undefined {
  return STAGE_REGISTRY.find((s) => s.id === key);
}

export const STAGE_ORDER: readonly string[] = STAGE_REGISTRY.slice()
  .sort((a, b) => a.order - b.order)
  .map((s) => s.id);
